include:
    - remote: 'https://gitlab.com/libreumg/ci-templates/-/raw/docker_modular/docker_modular/kaniko_build_push_auth_multi.yml'
stages:
    - kaniko_build_push_auth_multi

variables:
  kaniko_registry_user: "${PUBLIC_NEXUS_USER}"
  kaniko_registry_password: "${PUBLIC_NEXUS_PASSWORD}"
  kaniko_registry: "${PUBLIC_NEXUS}:56789"
  kaniko_registry_image: "${PUBLIC_NEXUS}:56789/ship_docker/dataquality/dataquier"
