include:
    - remote: 'https://gitlab.com/libreumg/ci-templates/-/raw/docker_modular/docker_modular/kaniko_build_push_auth_multi.yml'
stages:
    - kaniko_build_push_auth_multi

variables:
  kaniko_registry_user: "${user}"
  kaniko_registry_password: "${secret}"
  kaniko_registry: "packages.ship-med.uni-greifswald.de:56789"
  kaniko_registry_image: "packages.ship-med.uni-greifswald.de:56789/ship_docker/dataquality/dataquier"
