include: 
    - remote: 'https://gitlab.com/libreumg/ci-templates/-/raw/main/kaniko/kaniko_build_push_multi.yml'    
stages:
    - kaniko_build_push_multi

variables:
  kaniko_registry_image: "${PUBLIC_NEXUS}:56789/ship_docker/struckmann/dataquier-2-shiny"
